### ISSUE TITLE
[BUG] Screen touch on mobile devices results in TypeError

### ISSUE THREAD

**Issue by puhoshville** [Web-SyncPlay/Web-SyncPlay#15]
How to reproduce:
1. open any room on mobile device or in chrome in development mode as mobile device
2. do any touch on player screen
3. got an error

<img width="461" alt="image" src="https://user-images.githubusercontent.com/6560448/213627696-2cc4983f-022f-4853-9627-e09f3e04e81e.png">

```
TypeError: this is not a Date object.
    at getTime (<anonymous>)
    at so (framework-5f4595e5518b5600.js:1:60187)
    at co (framework-5f4595e5518b5600.js:1:60641)
    at Object.useState (framework-5f4595e5518b5600.js:1:66579)
    at t.useState (framework-5f4595e5518b5600.js:1:125433)
    at l ([id]-c3e0dd1c96b5a8f3.js:1:1445)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Wo (framework-5f4595e5518b5600.js:1:68979)
    at Ku (framework-5f4595e5518b5600.js:1:112703)
    at Li (framework-5f4595e5518b5600.js:1:98953)
```
```
TypeError: this is not a Date object.
    at getTime (<anonymous>)
    at so (framework-5f4595e5518b5600.js:1:60187)
    at co (framework-5f4595e5518b5600.js:1:60641)
    at Object.useState (framework-5f4595e5518b5600.js:1:66579)
    at t.useState (framework-5f4595e5518b5600.js:1:125433)
    at l ([id]-c3e0dd1c96b5a8f3.js:1:1445)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Wo (framework-5f4595e5518b5600.js:1:68979)
    at Ku (framework-5f4595e5518b5600.js:1:112703)
    at Li (framework-5f4595e5518b5600.js:1:98953)
```

**Comment by puhoshville** [comment]
My proposal on resolving this bug is implemented here: https://github.com/Web-SyncPlay/Web-SyncPlay/pull/14
